name: example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: shiki <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  json_l10n_annotation:
#    path: ../json_l10n_annotation
  json_l10n_annotation:
    git:
      url: git://github.com/ShikinChen/json_l10n_serializable.git
      path: json_l10n_annotation

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.10.0
#  json_l10n_serializable:
#    path: ../json_l10n_serializable
  json_l10n_serializable:
    git:
      url: git://github.com/ShikinChen/json_l10n_serializable.git
      path: json_l10n_serializable
