name: json_l10n_serializable
version: 0.0.1
description: >-
  将json转成本地化类工具
homepage: https://github.com/ShikinChen
author: Shiki
environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'
dependencies:
#  json_l10n_annotation:
#    path: ../json_l10n_annotation
  json_l10n_annotation:
    git:
      url: git://github.com/ShikinChen/json_l10n_serializable.git
      path: json_l10n_annotation
  source_gen: ^0.9.0+1

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.0
  test: ^1.0.0

